apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: location-discovery
  namespace: vibe-social
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: location-discovery
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
