apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-discovery
  namespace: vibe-social
spec:
  selector:
    matchLabels:
      app: location-discovery
  template:
    metadata:
      labels:
        app: location-discovery
    spec:
      containers:
        - name: location-discovery
          image: vibesocial/location-discovery
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1.0"
              memory: "1000Mi"
            requests:
              cpu: "0.75"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
